### PR TITLE
Fix from fastrlock cimport rlock to work

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/scoder/fastrlock/issues/3

### CODE REVIEW

**Comment by scoder** [comment]
Thanks, I'm accepting this pull request because it solves the problem at hand. But the underlying issue is in Cython. I'll see if I can get it fixed there.

**Comment by sonots** [comment]
I got you. Thank you!

**Comment by scoder** [comment]
I released 0.3 with this fix.

**Comment by sonots** [comment]
It worked. Thank you!

**Pull request merged**
