### PR TITLE
Add linux aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Add linux aarch64 wheel build support. 

Related to https://github.com/scoder/fastrlock/issues/12 @scoder Could you please review this PR?

### CODE REVIEW

**Comment by scoder** [comment]
lxml already has a better Makefile implementation that avoids duplicating the entire build script:

https://github.com/lxml/lxml/blob/5c8edfa39b0e31490a581740aaff44656ec72348/Makefile#L61-L65

Could you try to adapt that?

That said, I'd rather not run that build locally on my machine since the emulation makes it horribly slow. Would be nice to have Github Actions do it for me.

**Comment by odidev** [comment]
@scoder I have done the changes as per your suggestions. Please take a look.

**Comment by odidev** [comment]
@scoder, could you please review this PR? Thanks.

**Comment by scoder** [comment]
How very nice! Thanks!

**Comment by odidev** [comment]
@scoder, may I know the plan for releasing AArch64 wheels? Thanks.

**Comment by kmaehashi** [comment]
Great work, @odidev! I'm also interested in the aarch64 wheel availability as I'm planning to release [CuPy wheels for aarch64](https://github.com/cupy/cupy/issues/3196).

**Comment by scoder** [comment]
I'll push them out as soon as I have everything up and running. During the next days.

Looks like the PGO build is failing for aarch64, probably due to resource problems on the virtual machine. I'll see if I can reduce the benchmark run overhead.

**Comment by scoder** [comment]
It also seems worth building the wheels in separate GHA matrix jobs. Especially the AArch64 wheels take very long to build in the end.

**Pull request merged**
